### ISSUE TITLE
WebChain is using a non-unique Chain ID

### ISSUE THREAD

**Issue by suryanshkumr** [webchain-network/webchaind#1]
Webchain is using ChainID 101 which is not unique because EtherInc is using ChainID 101.

EtherInc first block was created on 2018-02-13 21:59:01 +0530 (https://explorer.einc.io/block/1)

WebChain first block was created on 2018-05-08 14:12:10 +0530 (https://explorer.webchain.network/block/1)

so as you can see EtherInc was running chainID 101 from Feb and WebChain using same chainid from May.

**Comment by lukaszmatczak** [comment]
Only issue I see with it is replay attack. But because Webchain and EtherInc don't share the same addresses (at least they shouldn't), it shouldn't cause any trouble.

**Comment by hackmod** [comment]
Please see https://github.com/ethereum-lists/chains/issues/25
